import hardhatEthers from "@nomicfoundation/hardhat-ethers";
import hardhatEthersChaiMatchers from "@nomicfoundation/hardhat-ethers-chai-matchers";
import hardhatMocha from "@nomicfoundation/hardhat-mocha";

export default {
  plugins: [hardhatEthers, hardhatEthersChaiMatchers, hardhatMocha],
  solidity: {
    // Exact version, no caret. IdentityProofVerifier.sol (generated by snarkjs) accepts >=0.7.0 <0.9.0.
    version: "0.8.37",
    settings: {
      optimizer: { enabled: true, runs: 200 },
      // Cancun is understood by every EVM the demo may run on, including in-browser ones.
      evmVersion: "cancun",
    },
  },
  paths: {
    tests: { mocha: "./test" },
  },
};
