// Demo identities. The identity number is a Turkish ID number generated by `tc-id`: it has
// a valid format and checksum, but it is random test data and does not belong to anyone on
// purpose. Name and date of birth are made up the same way.
import { generateTCID } from "tc-id";

const FIRST_NAMES = ["Deniz", "Ada", "Kerem", "Zeynep", "Mert", "Elif", "Can", "Selin", "Baran", "Defne", "Emre", "Lale"];
const LAST_NAMES = ["Yilmaz", "Kaya", "Demir", "Celik", "Sahin", "Arslan", "Aydin", "Ozturk", "Polat", "Koc", "Tuna", "Gunes"];

const pick = (items, random) => items[Math.floor(random() * items.length)];
const pad = (n) => String(n).padStart(2, "0");

/**
 * A new fake identity: { fullName, identityNumber, nationality, dateOfBirth }.
 * `random` is injectable for tests (a function returning a number in [0, 1)).
 */
export function newIdentity(random = Math.random) {
  const year = 1960 + Math.floor(random() * 45);
  const month = 1 + Math.floor(random() * 12);
  const day = 1 + Math.floor(random() * 28); // 28: every month has these days
  return {
    fullName: `${pick(FIRST_NAMES, random)} ${pick(LAST_NAMES, random)}`,
    identityNumber: generateTCID(),
    nationality: "TR",
    dateOfBirth: `${year}-${pad(month)}-${pad(day)}`,
  };
}
